In [28]:
import numpy as np
from scipy.linalg import eig, inv

### Eigendecomposition

In [21]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# calculate eigen decomposition
values,vectors = eig(A)

In [17]:
values

array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -9.75918483e-16+0.j])

In [18]:
vectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

### Confirm an eigenvector and eigenvalue

In [26]:
# Av = wv
B = A.dot(vectors[:,0])
print(B)
C = values[0]*vectors[:,0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537+0.j  -8.46653421+0.j -13.19443305+0.j]


### Reconstract original matrix

In [33]:
# H = P*(lambda*I)*inv(P)
P = vectors
P_inv = inv(P)
L = np.diag(values)

H = P.dot(L).dot(P_inv)
H.real

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

An n×n matrix which is diagonalizable must have a set of n linearly independent eigenvectors -- the columns of the diagonalizing matrix are such a set.

In general, if an n×n matrix has k distinct eigenvalues, then there may in general be anywhere between k and n linearly independent eigenvectors.

For any of this, it doesn't matter whether or not the eigenvalues are non-zero.

Correct, an n×n matrix which is diagonalizable must have a set of n linearly independent eigenvectors -- the columns of the diagonalizing matrix are such a set.

In general, if an n×n matrix has k distinct eigenvalues, then there may in general be anywhere between k and n linearly independent eigenvectors.

For any of this, it doesn't matter whether or not the eigenvalues are non-zero.