In [35]:
import numpy as np

## Standartization

### StandardScaler

In [36]:
# Let's do it manually 

x = np.array([0,0,1,1])
std = np.std(x)
mean = np.mean(x)
for i in x:
    print((i-mean)/std)


-1.0
-1.0
1.0
1.0


In [37]:
# Using sklearn 
from sklearn.preprocessing import StandardScaler

data = [[0, 0], [0, 0], [1, 1], [1, 1]]

# initialize scaler
scaler = StandardScaler()

# fit to data
print(scaler.fit(data), "\n")

print(scaler.mean_)
print(scaler.scale_, "\n")

# perform standardization
print(scaler.transform(data), "\n")


# perform standardization for new samples
print(scaler.transform([[2, 2]]))

StandardScaler() 

[0.5 0.5]
[0.5 0.5] 

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]] 

[[3. 3.]]


In [38]:
# The code above can be written more efficiently(this one fits and transforms sequentially)
from sklearn.preprocessing import StandardScaler

data = [[0, 0], [0, 0], [1, 1], [1, 1]]

scaler = StandardScaler()

scaler.fit_transform(data)


array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

### MinMaxScaler

In [39]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

min_max_scaler = MinMaxScaler()
print(min_max_scaler.fit(data), '\n')

print(min_max_scaler.data_max_, '\n')

print(min_max_scaler.transform(data), '\n')




print(min_max_scaler.transform([[2, 2]]), '\n')

print(min_max_scaler.scale_)
print(min_max_scaler.min_)

MinMaxScaler() 

[ 1. 18.] 

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]] 

[[1.5 0. ]] 

[0.5    0.0625]
[ 0.5   -0.125]


In [98]:
X = np.arange(4)
X

array([0, 1, 2, 3])

In [99]:
y = np.exp(2 * X)
y

array([  1.        ,   7.3890561 ,  54.59815003, 403.42879349])