In [16]:
import numpy as np
from scipy.linalg import svd, eig

#### 1) sigma s in SVD is square root of lambda which is eigenvalue in eigendecomposition. That is s = sqrt (lambda)
#### 2) Vh (v transpose) is set of eigenvectors which are found in eigendecomposition
#### 3) for U, better use computer to calculate. It is a tedious calculation.

In [87]:
# Let's factorize this matrix usin SVD
A = np.array([[1,1],
              [0,1],
              [-1,1]])

In [88]:
U,s,Vh = svd(A)

In [89]:
# singular values, hierarchically ordered
s

array([1.73205081, 1.41421356])

In [90]:
# left singular vector, each coloumn orthogonal and has unit length
U

array([[-0.57735027, -0.70710678,  0.40824829],
       [-0.57735027,  0.        , -0.81649658],
       [-0.57735027,  0.70710678,  0.40824829]])

In [91]:
# right singular vector
Vh

array([[-0., -1.],
       [-1., -0.]])

In [92]:
s = np.diag(s)
s

array([[1.73205081, 0.        ],
       [0.        , 1.41421356]])

In [93]:
s = np.append(s,[[0,0]], axis = 0)
s

array([[1.73205081, 0.        ],
       [0.        , 1.41421356],
       [0.        , 0.        ]])

#### Here, we can confirm our decomposition and calculate our original matrix

In [94]:
U.dot(s).dot(Vh)

array([[ 1.,  1.],
       [ 0.,  1.],
       [-1.,  1.]])

#### Here, we can see the relationship of eigendecomposition and svd

In [21]:
# here we see that trnspose of eigenvectors are equal to those of SVD. The only difference in negative and positive 
# sign. That does not make difference in calculations.

values, vectors = eig(np.matrix.transpose(A).dot(A))
print(values.real)
print(vectors)

[2. 3.]
[[1. 0.]
 [0. 1.]]
